arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - robotiq_85_left_knuckle_joint

gazebo_ros_control/pid_gains:
  joint1:   {p: 1000, i: 0.01, d: 10.0}
  joint2:   {p: 1000, i: 0.01, d: 10.0}
  joint3:   {p: 1000, i: 0.01, d: 10.0}
  joint4:   {p: 1000, i: 0.01, d: 10.0}
  joint5:   {p: 1000, i: 0.01, d: 10.0}
  joint6:   {p: 1000, i: 0.01, d: 10.0}
  robotiq_85_left_knuckle_joint:  {p: 1000, i: 0.0, d: 0.0}