image: /home/yang/yang_ws/src/arm_gazebo/innfos_control/gazebo_control/config/map_without_door.pgm
resolution: 0.050000
origin: [-10.000000, -10.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

